project_id = "tqvzdgysxjrjtwvkhkli"

[functions.seed-projects]
verify_jwt = false

[functions.seed-users]
verify_jwt = false

[functions.generate-tasks-v2]
verify_jwt = false

[functions.generate-role-questions]
verify_jwt = false

[functions.generate-role-questions-v2]
verify_jwt = false

[functions.generate-playbook]
verify_jwt = false

[functions.generate-project-roles]
verify_jwt = false

[functions.generate-task-completion-questions]
verify_jwt = false
